### ISSUE TITLE
View widget

### ISSUE THREAD

**Issue by ElecSmurf** [joaopegoraro/mvvm_riverpod#1]
Hi Joa,

I like your implementation, nice work!

Would it be possible to create a View class where you would have:

class SomeWidget extends View<SomeWidgetViewModel> {

   @override
   AutoDisposeProvider<SomeWidgetViewModel> someWidgetViewModelProvider() => someWidgetViewModelProvider;

   @override
  Widget buildWidget(
      BuildContext context, SomeWidgetViewModel viewModel) {
         return ...
      }
   );

}

a bit like what's done here:
https://github.com/MinhMark123123/maac/tree/main/packages/maac_mvvm_with_riverpod/lib/src

This would further reduce boilerplate code in the widgets

**Comment by joaopegoraro** [comment]
Not a bad idea, will look into it. Will probably call `ViewModelWidget` or something.

**Comment by joaopegoraro** [comment]
Better late than never. Added the `ViewModelWidget` in the new 1.2.0 version
